FROM ydjharbor.jingzhuan.cn/public/hyperf:7.4-alpine-v3.11-cli

WORKDIR /home/wwwroot
ADD . .
RUN composer config -g repo.packagist composer https://mirrors.aliyun.com/composer && \
    composer install --no-dev -o && php bin/hyperf.php

EXPOSE 9501 9502

ENTRYPOINT ["php", "/home/wwwroot/bin/hyperf.php", "start"]
